### ISSUE TITLE
Portal/Product Feedback - Missing Key Data and Ideas for Organization

### ISSUE THREAD

**Issue by jturner181** [IBM-Bluemix-Docs/sap-hana#2]
The majority of SAP clients (90+%) has legacy environments and will have for several years. I would like to see IBM Cloud open up the marketing material and product direction to be more than SAP HANA only. While SAP HANA is the future of the SAP product line, the legacy systems (ECC, ERP6.0, BI, BPC, CRM, SRM, etc etc etc) are primarily non-HANA systems. IBM does provide compute for these systems, but clients have complained to me that the portal and supporting documentation seems to be SAP HANA focused only. Even SAP HANA clients have a need to support some products that are not converted to SAP HANA yet - not all SAP software runs on HANA (nor will for many years). 

Recommendation:
1.  Change the name from SAP-HANA to 'SAP on IBM Cloud'
2.  Create SAP-HANA to be a sub component to 'SAP on IBM Cloud'
3.  Allow SAP instances to be built on traditional VPC or in-memory VPC (or bare metal)
4.  Allow Middleware needed for SAP Instances in the SAP portal screens (standard VPC add to cart from SAP portal)

Ideally we would see 'SAP for IBM Cloud' as the primary screen - and from that screen, have SAP HANA, SAP ERP, SAP Middleware, non-SAP Systems as a set of options that SAP clients can order to create an entire ecosystem, tied in with links to Cloud Paks, OpenShift, Watson API for SAP, Veem Backup for SAP, HA for SAP Systems (HANA and non-HANA), DR for SAP Systems (for entire ecosystem), Power for SAP (HANA and non-HANA), and eventually API connector to SAP Download site so clients can download/install better/faster/easier. 

My background?
-25+ Years of SAP 
-Selling SAP on IBM Cloud (pre-cloud, virtualized, multi-tenant, SCE+ Cloud, and now Softlayer) for past 10+ Years - 100's of client conversations
-Cloud Channel Sales Leader, North America (current role) - business partner discussions

If we could organize the SAP Products/Offerings in this way, it would allow us to sell Direct or Channel much easier, allow clients to have more confidence in our SAP offerings, and simplify the portal lookup/ordering process, especially with all direct or VAR partners who have limited SAP skills. 

This is the first wave of changes I would love to see - If we can get these done, then I have another dozen or two changes ;)

Take care IBMer's!

- Jamie Turner
Cloud Channel Sales Leader, North America
IBM Global Markets
jamie.turner@us.ibm.com

**Comment by DebraCip** [comment]
jturner181, I'm the technical writer responsible for the SAP content in the IBM Cloud catalog. Our content isn't focused on SAP HANA, we have three guides specific to SAP NetWeaver. It sounds like you're looking for changes specific to how a customer orders SAP products (software). We, IBM, don't have the SAP software for the customers. We're just providing the compute environment on which the customer can download their SAP software.

We have content HA (https://cloud.ibm.com/docs/infrastructure/sap-netweaver?topic=sap-netweaver-ha) and are working on finalizing the content for Veeam Backup. Power for SAP is also in the works, and we're working towards VPC. 

Here is the link where you can see all of our to date SAP-related content - https://cloud.ibm.com/docs/bare-metal?topic=bare-metal-sap-cert-infrastructure. Please let me know if there's anything else I can help you with.
